// src/components/global/header.jsx
import React from 'react';
import { Link } from "gatsby"
import styled from 'styled-components';
import { breakpointFrom, breakpointTo, breakpoints } from './StyledBreakpoints';
import Memoji from './memoji'

const Header = () => {
  return(
    <>
      <header className="sticky top-0 bg-white p-12 grid grid-cols-12">
        <nav class="col-span-6 flex justify-start items-center">
          <Link to="/" className="no-underline text-gray-600 hover:text-gray-800 mr-4">Home</Link>
          <Link to="/posts" className="no-underline text-gray-600 hover:text-gray-800 mr-4">Posts</Link>
        </nav>
        <div className="logo col-span-6 flex justify-end items-center">
          <Link to="/" className="font-bold text-gray-600">
            Joel Krause
          </Link>
        </div>
      </header>
      </>
  )
}

export default Header

// components/Header.vue
<template>
    <header class="p-12">
        <div class="grid grid-cols-12">
            <div class="col-span-6">
                <nuxt-link to="/" class="font-display text-lg">
            Joel Krause
                </nuxt-link>
            </div>
            <div class="col-span-6">
                <nav>
                    <ul class="flex justify-end">
                        <li class="mr-6">
                            <nuxt-link to="/" class="hover:to-blue-600">Home</nuxt-link>
                        </li>
                        <li>
                            <nuxt-link to="/posts" class="hover:to-blue-600">Posts</nuxt-link>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
</template>
